version: '3.4'

networks:
  sovos-invoicing-dev:
    driver: bridge

services:
  sovos-invoicing:
    image: sovos-invoicing:latest
    container_name: sovos-invoicing
    depends_on:
      - "postgres"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:5000"
    environment:
      - ASPNETCORE_URLS=http://*:5000

    networks:
      - sovos-invoicing-dev

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./db_volume:/var/lib/postgresql/data
    networks:
      - sovos-invoicing-dev
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "trust"